---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian10
  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure awscli is installed.
  - >
    ${DOCKER} aws --version
    && (echo 'awscli is installed' && exit 0)
    || (echo 'awscli is not installed' && exit 1)

  # Check autocomplete is installed (this does not work in docker container somehow)
  # - ${DOCKER} complete -p | grep aws_completer

after_failure:
  - ${DOCKER} aws --version
  - ${DOCKER} which aws
  - ${DOCKER} complete -p

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
