
#- set_fact:
#    _awscli_profiles[{{item.user}}][]: '{{ '

- name: Ensure aws config dir exists
  no_log: true
  file:
    path: ~/.aws
    state: directory
    owner: '{{ item.user }}'
  become: true
  become_user: '{{ item.user }}'
  when: item.profiles is defined
  with_items: '{{ awscli_profiles }}'

- name: Set config
  no_log: true
  template:
    src: config
    dest: ~/.aws/credentials
    owner: '{{ item.user }}'
  become: true
  become_user: '{{ item.user }}'
  when: item.profiles is defined
  with_items: '{{ awscli_profiles }}'
