---

- name: Install required apt packages
  apt:
    pkg: '{{ item }}'
    state: present
    cache_valid_time: 86400
  with_items: '{{ awscli_apt_packages }}'

- name: Install awscli
  pip:
    name: awscli
    state: present
  with_items: '{{ awscli_pip_packages }}'