---

- name: Install required apt packages
  apt:
    pkg: '{{ awscli_apt_packages }}'
    state: present
    cache_valid_time: 86400

- name: Install awscli
  pip:
    name: awscli
    state: present
  with_items: '{{ awscli_pip_packages }}'