---

- name: Install required apt packages
  apt:
    pkg: '{{ item }}'
    state: present
  with_items: '{{ awscli_apt_packages }}'

- name: Install awscli
  pip:
    name: awscli
    state: present
